### PR TITLE
README.md updated and formatted

### PR DESCRIPTION
**Pull request by kartike66**
Added step by step implementation of deploying and calling the contacts locally using forge, anvil and cast.

### CODE REVIEW

**Review by seachellemz — CHANGES_REQUESTED** [review]
I like the additional detail that you are including.  Please be sure to remove or mask any/all private keys in your screenshots.

**Comment by kartike66** [comment]
@seachellemz none of the keys are real. It is a mock blockchain node with fake accounts, fake keys, and fake ether.

**Comment by seachellemz** [comment]
Sorry.  I didn't realize they were mock keys.

**Review by seachellemz — APPROVED** [review]

**Comment by kartike66** [comment]
No you're right, ideally I should use environment variables. Like at least for readability.

**Pull request merged**
